### ISSUE TITLE
Top level assembly

### ISSUE THREAD

**Issue by AntonEvmenenko** [JesusFreke/lalboard#10]
Hi @JesusFreke!

Let me thank you for creating this very interesting project!

As I understand, you published the Fusion 360 scripts only for individual parts, but currently repository doesn't contain a script that would allow you to generate the entire keyboard:

![lalboard](https://camo.githubusercontent.com/4a7a5cdcfd2b3e958aa8ecabe46951a5e768f9e2/68747470733a2f2f6a657375736672656b652e6769746875622e696f2f6c616c626f6172642f6c616c626f6172642e6a7067)

If you added such a script, it would be very cool :) 

Of course, if you have your own opinion about it (for example, you do not want to publish this project completely), then it's okay, in this case just close this issue please.

**Comment by JesusFreke** [comment]
I did have some scripts for the individual cluster assemblies at one point, but they got out of date as things changed. But the entire project is published. I don't have some hidden script that I'm keeping from you ;)

**Comment by AntonEvmenenko** [comment]
> I don't have some hidden script that I'm keeping from you ;)

Haha :)

Ok, thanks for your answer!
