### ISSUE TITLE
Cluster keywell geometry

### ISSUE THREAD

**Issue by scruper** [JesusFreke/lalboard#14]
Hi, I'm migrating your project to CadQuery + QMK at the moment and have a question.

Is a geometry at the bottom of the keywell more complicated for tactility reasons?

![image](https://user-images.githubusercontent.com/42234951/184475704-ddea409d-0de2-41c2-9ac3-660cbd582d48.png)

**Comment by JesusFreke** [comment]
This geometry helps to ensure there isn't a steep overhang angle, for better printability. But I'm not totally sure it's necessary, at that scale.

**Comment by scruper** [comment]
Thank you!

**Comment by wirekang** [comment]
@scruper Hi. I'm trying to migrate fscad files into cadquery. Can you share your works or give me some advice?
