### ISSUE TITLE
Please create a Kickstarter/Indiegogo/etc

### ISSUE THREAD

**Issue by hillelcoren** [JesusFreke/lalboard#3]
I would love to buy one of these, how can I help make it happen?

**Comment by JesusFreke** [comment]
haha, no :)

I'm happy to put the design up and let people do what they want with it, but I don't particularly want to spend my free time trying to finagle a crowd funding campaign, or building these to sell. Plus, it's honestly not... polished enough to be sold/marketed as an off-the-shelf consumer item.

I might be convinced to sell the raw 3d printed/vinyl cut parts or something though.
