### ISSUE TITLE
Custom handrest?

### ISSUE THREAD

**Issue by bofh** [JesusFreke/lalboard#7]
Hello, could you please outline the process and provide some tips you used to mold custom handrest? What should be the optimal hand position, height above the table, etc.?

**Comment by JesusFreke** [comment]
I molded it out of some plasticene clay first, and then scanned it in using the meshroom photogrammetry software. I had never used it before, but used [the tutorial](https://www.youtube.com/watch?v=1D0EhSi-vvc) that Prusa published. Once it was scanned in, I think I cleaned up the mesh in the meshlab software, and then imported it into fusion 360 and simplified the mesh, and added the rectangular cutout in the bottom for the central electronics tray. I don't recall the exact process/steps offhand, sorry :)

As far as the shape, you can take a look at the existing hand rests to get an idea. It needs to be wide enough to hold the tray of course. But other than that, it's mostly up to personal taste? Just kinda whatever feels right for your hand. heh. I'm certainly no ergonomic specialist :)

I would recommend getting the finger and thumb clusters made and at least mechanically assembled and placed onto the steel sheet, and then molding the custom clay handrest in place, so you can see how it feels with your fingers actually in place on the keys, etc.
