### ISSUE TITLE
CAD Models?

### ISSUE THREAD

**Issue by thecheatscalc** [JesusFreke/lalboard#8]
I apologize if these are available somewhere, but would you be interested in adding your CAD models that generated the STLs? If they're hosted elsewhere, would you mind adding a link in the docs?

**Comment by JesusFreke** [comment]
[lalboard.py](https://github.com/JesusFreke/lalboard/blob/master/lalboard.py) is where all of the models are defined. It uses my [fscad framework](fscad.org) for fusion 360. The design() method at the end of the file is the main entry point, where you can uncomment a specific part to generate.

**Comment by thecheatscalc** [comment]
Aha, I completely missed that. I'll have to try and pull the models in with your fscad framework later. Thanks for clarifying!
